### ISSUE TITLE
PRÁCTICA 4: MODELO DE NEGOCIOS 

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-equipo-hjfs#1]

**Comment by FedericoVictorianoSierra** [comment]
[Práctica 4 Modelo de Negocios (Federico Victoriano Sierra).pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-equipo-hjfs/files/9579190/Practica.4.Modelo.de.Negocios.Federico.Victoriano.Sierra.pdf)

**Comment by Heidi-19** [comment]
[Práctica 4 Modelo de Negocios_HeidiLucyBautistaSanjuan.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-equipo-hjfs/files/9579176/Practica.4.Modelo.de.Negocios_HeidiLucyBautistaSanjuan.pdf)

**Comment by JoseABCruz** [comment]
[Práctica 4 Modelo de Negocios (José Antonio Balbuena Cruz).pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-equipo-hjfs/files/9579211/Practica.4.Modelo.de.Negocios.Jose.Antonio.Balbuena.Cruz.pdf)

**Comment by SANDRAVELASCO** [comment]
[Práctica 4 Modelo de Negocios.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-equipo-hjfs/files/9618842/Practica.4.Modelo.de.Negocios.pdf)

**Comment by Elisahadad** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
